---
title: "Environmental Data Science"
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Events

- [Environmental Data Science Summit - February 6 - 8, 2024 - Santa Barbara, California](https://www.nceas.ucsb.edu/environmental-data-science-summit)

- [Environmental Data Science Summit - February 7 & 8, 2023 - Santa Barbara, California](https://eds-summit.github.io/)

- [Environmental Data Science Summit - February 8-9, 2022 | Santa Barbara, California](https://eds-summit.github.io/)


## Groups

- [EcoDataScience](https://eco-data-science.github.io/) - [GitHub](https://github.com/eco-data-science), [Slack](https://join.slack.com/t/ecodatascience/shared_invite/enQtNTE1MjAxMTU2NjQwLTZmYjQ5OGIyNjM0YTM4ZDhiMTA2Njc1Mjg2YjFlYWEwZDhlNjJmMTE3MzI2ZmM4ZTJhYTczNmZhYjk3YTI5NjU)

## Opportunities

- [SEEKCommons Fellowship](https://seekcommons.org/fellowship-application.html)


## Books

- [Environmental Data Analysis - An Introduction with Examples in R](https://link.springer.com/book/10.1007/978-3-030-55020-2), by Carsten Dormann

- [Introduction to Environmental Data Science](https://bookdown.org/igisc/EnvDataSci/), by Jerry Davis (SFSU Institute for Geographic Information Science) -  <https://doi.org/10.1201/9781003317821>


- [Environmental Data Analysis - Methods and Applications](https://www.degruyter.com/document/doi/10.1515/9783111012681/html?lang=en), by Zhihua Zhang.

## Articles

### About Environmental Data Science

- [Data Science of the Natural Environment: A Research Roadmap](https://doi.org/10.3389/fenvs.2019.00121)

- [A career in environmental informatics and environmental data science](https://doi.org/10.1002/fee.2038)


- [Data Analytics for Environmental Science and Engineering Research](https://doi.org/10.1021/acs.est.1c01026)

- [Machine Learning and Data Analytics for Environmental Science: A Review, Prospects and Challenges](https://iopscience.iop.org/article/10.1088/1757-899X/955/1/012107/meta)

- [Evolution of machine learning in environmental science — A perspective](https://doi.org/10.1017/eds.2022.2)

- [Why we need to focus on developing ethical, responsible, and trustworthy artificial intelligence approaches for environmental science](https://doi.org/10.1017/eds.2022.5)

### About Data Science

- [50 years of Data Science](https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1384734) - David Donoho


## Journals

- [Environmental Data Science - ISSN 2634-4602](https://www.cambridge.org/core/journals/environmental-data-science)


## R Packages

- [CRAN Task View: Analysis of Ecological and Environmental Data](https://cran.r-project.org/web/views/Environmetrics.html)


## Courses

### Free courses

- [Data Science for Ecologists and Environmental Scientists](https://ourcodingclub.github.io/course)

- [Data Carpentry Ecology Curriculum](https://datacarpentry.org/lessons/#ecology-workshop)

### Disciplinas de pós-graduação no Brasil

- [PRPG CIAMB - UFG](https://ciamb.prpg.ufg.br/) - [Análise de Dados Ambientais](https://files.cercomp.ufg.br/weby/up/104/o/An%C3%A1lise_de_Dados_Ambientais.pdf) - [Material da disciplina](https://lhmet.github.io/adar-ebook/)

### Academic courses (outside Brazil)

- [University of California, Santa Barbara - Bren School of Environmental Science & Management - Master of Environmental Data Science](https://bren.ucsb.edu/masters-programs/master-environmental-data-science)

- [Courses at Yale School of Environment](https://environment.yale.edu/data-science/courses/)

- [Imperial College London - Msc Environmental Data Science and Machine Learning](https://www.imperial.ac.uk/study/pg/earth-science/environmental-data-science-machine-learning/)


### Content from courses at the Master of Environmental Data Science (MEDS) - Bren School

- [Reference](https://my.sa.ucsb.edu/catalog/Current/CollegesDepartments/bren/Index.aspx?DeptTab=Graduate)

- [About MEDS](https://ucsb-meds.github.io/)

- [All courses](https://ucsb-meds.github.io/courses.html)

- [EDS 211 Team Science, Collaborative Analysis and Project Management](https://bbest.github.io/eds211-team/)   
- [EDS 212 Essential Math for Environmental Data Science](https://allisonhorst.github.io/EDS_212_essential-math/) 
- [EDS 213 Metadata Standards, Data Modeling and Data Semantics](https://brunj7.github.io/EDS-213-metadata/) 
- [EDS 214 Analytical Workflows and Scientific Reproducibility](https://brunj7.github.io/EDS-214-analytical-workflows/) 
- [EDS 215 Introduction to Data Storage and Management](https://jamesfrew.github.io/EDS_215_data_management/) 
- [EDS 216 Meta-analysis and Systematic Reviews](https://ucsbhydro.github.io/EDS_216_meta-analysis/) 
- [EDS 220 Remote Sensing and Environmental Data](https://samanthastevenson.github.io/EDS220_site/) 
- [EDS 221 Scientific Programming Essentials](https://allisonhorst.github.io/EDS_221_programming-essentials/) 
- [EDS 222 Statistics for Environmental Data Science](https://tcarleton.github.io/EDS-222-stats/) 
- [EDS 223 Spatial Analysis for Environmental Data Science](https://jamesfrew.github.io/EDS_223_spatial_analysis/) 
- [EDS 230 Modeling Environmental Systems](https://naomitague.github.io/ESM232_course/) 
- [EDS 231 Text and Sentiment Analysis for Environmental Problems](https://maro406.github.io/EDS_231-text-sentiment/) 
- [EDS 232 Machine Learning in Environmental Science](https://bbest.github.io/eds232-ml/) 
- [EDS 240 Data Visualization and Communication](https://bren.ucsb.edu/courses/eds-240) 
- [EDS 241 Environmental Policy Evaluation](https://bren.ucsb.edu/courses/eds-241) 
- [EDS 242 Ethics and Bias in Environmental Data Science](https://bren.ucsb.edu/courses/eds-242) 
